name: Prace.js
on:
  pull_request:
    types: [
        'unlabeled',
    ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: innerspacetrainings/Prace.js@master
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}